language: node_js
node_js:
  - "14"
script:
  - "echo ******Installing dependencies******"
  - "npm install"
  - "npm run build"
  - "npm run dev &"
  - "npx cypress run"
  - "kill $(jobs -p) || true"
